#!/usr/bin/env bash
#Install/Configure nginx With a "301 Moved Permanently" Redirection

apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
chown -R "$USER":"$USER" /var/www/html/index.nginx-debian.html
chmod -R 755 /var/www
echo "Holberton School" > /var/www/html/index.nginx-debian.html
printf %s "server {
       listen 80 default_server;
       listen [::]:80 default_server;
       root /var/www/html ;
       index index.html index.htm index.nginx-debian.html;
       server_name _;
       location / {
       		try_files \$uri \$uri/ =404;
	}
	location /redirect_me{
		 error_page 404 =301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}
}" > /etc/nginx/sites-available/default
service nginx restart
