#!/usr/bin/env bash
#Nginx configure header response

apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
chown -R "$USER":"$USER" /var/www/html/index.nginx-debian.html
chmod -R 755 /var/www
sed -i "44i  add_header X-Served-By  ""$HOSTNAME""" /etc/nginx/sites-available/default

service nginx restart
