#!/usr/bin/env bash
#Nginx configure header response

apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Holberton School" > /var/www/html/index.nginx-debian.html
printf %s "server {
       listen 80 default_server;
       listen [::]:80 default_server;
       
       root /var/www/html ;
       index index.html index.htm index.nginx-debian.html;
       
       server_name _;
       
       location / {
       		add_header X-Served-By  $HOSTNAME;
       		try_files \$uri \$uri/ =404;
	}
}"> /etc/nginx/sites-available/default
service nginx restart
