#!/usr/bin/env bash
#install configure HaProxy

sudo apt update
sudo apt-get  -y install haproxy

printf %s "
frontend haproxy
    bind *:80
    mode http
    default_backend  cuore
backend cuore
    balance roundrobin
        server 1407-web-01 34.73.158.219:80 check
        server 1407-web-02 34.75.32.130:80 check
"        >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
