#!/usr/bin/env bash
#Bash script that displays the content of the file /etc/passwd.

#echo "root:x:0:0:root:/root:/bin/bash" | cut -d ":" -f 1,3,6

while read -r p
do
    echo "$p" | cut -d ":" -f 1,3,6
done < /etc/passwd
