#!/usr/bin/env bash
#Bash script that loops from 1 to 10 With specifications.
i=1
while [ "$i" -lt 11 ]
do
    if [ "$i" -eq 4 ]
    then
	echo "bad luck"
    elif [ "$i" -eq 8 ]
    then
	echo "good luck"
    else
	echo "Holberton School"
    fi
    ((i++))
done
