#!/usr/bin/env bash
# The command suppose that we are  on the container shell..

service apache2 start

#the following commented line is correct( executed from host)
#docker exec -i "$(docker  ps -q --filter ancestor=holbertonschool/265-0)"  service apache2 start

