#!/usr/bin/env bash
#Using what you did for task #1, make your fix short and sweet.

sed -i 's/80/8080/' /etc/nginx/sites-enabled/default
chown nginx:nginx /etc/nginx/ -R
chmod +rw /etc/nginx/nginx.conf
su -c 'service nginx start' nginx
